import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home(props) {
	const { langList, teamList } = props
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<heading>
				<h1 className={styles.title}>Разговорники</h1>

				<p className={styles.description}>
					Приветствуем, друзья! На этом сайте вы найдете разговорники народов
					России. Сайт создан в рамках проекта "Всяк сущий в ней язык",
					выполняемого Ассамблеей народов России в партнёрстве с Высшей школой
					экономики и поддержанного Фондом президентских грантов.
				</p>
			</heading>

			<main className={styles.main}>
				<section className={styles.langs}>
					<div className={styles.grid}>
						{langList.map(lang => {
							const { title, description } = lang
							return (
								<a href='https://nextjs.org/docs' className={styles.card}>
									<h2>{title} &rarr;</h2>
									<p>{description}</p>
								</a>
							)
						})}
					</div>
				</section>
				<section className={styles.team}>
					<h1 className={styles.title}>Команда</h1>
					<div className={styles.grid}>
						{teamList.map(person => {
							const { name, description, image } = person
							return (
								<a href='https://nextjs.org/docs' className={styles.card}>
									<img src={image} className={styles.avatar} />
									<h2>{name}</h2>
									<p>{description}</p>
								</a>
							)
						})}
					</div>
				</section>
			</main>

			<footer className={styles.footer}>(c) 2022</footer>
		</div>
	)
}

export async function getStaticProps(context) {
	const langList = [
		{
			title: 'Хантыйский',
			description:
				'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ipsa!'
		},
		{
			title: 'Нанайский',
			description:
				'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ipsa!'
		},
		{
			title: 'Мокшанский',
			description:
				'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ipsa!'
		},
		{
			title: 'Карельский',
			description:
				'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ipsa!'
		}
	]
	const teamList = [
		{
			name: 'Алексей Козлов',
			image: 'https://joeschmoe.io/api/v1/jake',
			description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
        Quo quam obcaecati temporibus ipsa, mollitia molestiae officiis esse iure. Saepe, eum.`
		},
		{
			name: 'Василий Харитонов',
			image: 'https://joeschmoe.io/api/v1/jean',
			description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
        Quo quam obcaecati temporibus ipsa, mollitia molestiae officiis esse iure. Saepe, eum.`
		},
		{
			name: 'Динара Степина',
			image: 'https://joeschmoe.io/api/v1/jess',
			description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
        Quo quam obcaecati temporibus ipsa, mollitia molestiae officiis esse iure. Saepe, eum.`
		},
		{
			name: 'Мария Коновалова',
			image: 'https://joeschmoe.io/api/v1/jeane',
			description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
        Quo quam obcaecati temporibus ipsa, mollitia molestiae officiis esse iure. Saepe, eum.`
		}
	]

	return {
		props: {
			langList,
			teamList
		} // will be passed to the page component as props
	}
}
